name: Run Tests
on:
  push:
    branches:
      - main
  workflow_call: # Make this workflow callable from other workflows
  workflow_dispatch: # Make this workflow runnable on github

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11.*, 12.*, 13.*]
        include:
          - laravel: 13.*
            testbench: 11.*
          - laravel: 12.*
            testbench: 10.*
          - laravel: 11.*
            testbench: 9.*
        exclude:
          - php: 8.2
            laravel: 13.*
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Prepare App
        uses: michiruf/laravel-ci/prepare-app@main
        with:
          coverage: true
          php-version: ${{ matrix.php }}

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
          
      - name: Install testbench dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: List installed dependencies
        run: composer show -D

      - name: Run Tests
        run: vendor/bin/pest -v --coverage --ci
